"""run_study.py — one command, one JSON file, one reproducible claim set.

    python run_study.py --ranks ranks --out data/study.json

Everything the web explorer shows comes out of this file, so the page can never
show a number that was not computed here.  That is the whole point: the demo
stops being a demo the moment its numbers have a provenance.
"""

from __future__ import annotations

import argparse
import json
import math
import platform
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from minitok import MiniTok
import metrics as M
import stats as S
import stimuli as ST
import vocab_audit as VA

ENCODINGS = ["cl100k_base", "o200k_base"]


def _jsonable(obj):
    """NaN/Inf are legal in Python json.dumps but illegal in JSON.parse."""
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    if isinstance(obj, dict):
        return {k: _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_jsonable(v) for v in obj]
    return obj


def git_rev() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "unversioned"


def run(ranks_dir: Path, out: Path, encodings=ENCODINGS) -> dict:
    encs = {n: MiniTok.from_ranks_file(ranks_dir / f"{n}.js", name=n) for n in encodings}
    rows_by_enc: dict[str, list[dict]] = {}
    corpus_ids: dict[str, list[int]] = defaultdict(list)

    design = ST.expand()
    for name, enc in encs.items():
        rows = []
        for cell in design:
            m = M.text_metrics(enc, cell["text"])
            m["pieces"] = enc.pieces(cell["text"])
            m.update({k: v for k, v in cell.items() if k != "text"})
            m["encoding"] = name
            rows.append(m)
            corpus_ids[name].extend(enc.encode(cell["text"]))
        rows_by_enc[name] = rows

    # ---- inferential layer -------------------------------------------
    analysis = {}
    for name, rows in rows_by_enc.items():
        per_cat = {}
        cats = sorted({r["category"] for r in rows})
        for cat in cats:
            sub = [r for r in rows if r["category"] == cat]
            per_cat[cat] = S.decompose(sub, "n_tokens")
        analysis[name] = dict(
            overall=S.decompose(rows, "n_tokens"),
            overall_fallback=S.decompose(rows, "n_byte_fallback"),
            by_category=per_cat,
            renyi_efficiency=M.renyi_efficiency(corpus_ids[name]),
            attested_premium=S.contrast(
                rows, "n_tokens",
                {"script": "trad", "lexicon": "tw"},
                {"script": "simp", "lexicon": "cn"},
                relative=True),
        )

    # ---- construction probes ------------------------------------------
    cx = []
    for probe in ST.CONSTRUCTION_PROBES:
        entry = dict(probe)
        for name, enc in encs.items():
            entry[name] = {
                "canonical": enc.pieces(probe["canonical"]),
                "variant": enc.pieces(probe["variant"]),
                "canonical_n": len(enc.encode(probe["canonical"])),
                "variant_n": len(enc.encode(probe["variant"])),
                # is the whole canonical form a single token?
                "canonical_is_unit": len(enc.encode(probe["canonical"])) == 1,
            }
        cx.append(entry)

    # ---- vocabulary audit ---------------------------------------------
    audit = {name: dict(coverage=VA.coverage_asymmetry(enc),
                        profile=VA.length_profile(enc))
             for name, enc in encs.items()}

    payload = dict(
        meta=dict(
            generated=datetime.now(timezone.utc).isoformat(timespec="seconds"),
            git=git_rev(),
            python=platform.python_version(),
            n_items=len(ST.ITEMS),
            n_cells=len(design),
            encodings=encodings,
            note="Generated by run_study.py. Do not hand-edit.",
        ),
        hypotheses=ST.CATEGORY_HYPOTHESES,
        items=[{k: v for k, v in vars(i).items()} for i in ST.ITEMS],
        design=design,
        rows=rows_by_enc,
        analysis=analysis,
        constructions=cx,
        vocab_audit=audit,
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(_jsonable(payload), ensure_ascii=False, indent=1,
                              allow_nan=False), encoding="utf-8")
    return payload


def summarise(payload: dict) -> None:
    for enc, a in payload["analysis"].items():
        print(f"\n=== {enc} " + "=" * (50 - len(enc)))
        o = a["overall"]
        print("  字形效果 trad - simp      :", S.fmt(o["script_trad_minus_simp"], " tok"))
        print("  詞彙效果 tw - cn          :", S.fmt(o["lexicon_tw_minus_cn"], " tok"))
        print("  詞彙效果 hk - cn          :", S.fmt(o["lexicon_hk_minus_cn"], " tok"))
        print("  交互作用 tw               :", S.fmt(o["interaction_tw"], " tok"))
        nb = payload["analysis"][enc]["overall_fallback"]["script_trad_minus_simp"]
        print("  byte-fallback trad - simp :", S.fmt(nb, " tok"))
        nv = o["naive_v1_tw_over_cn_relative"]
        print(f"  v1「方言稅」(TW vs CN)     : {100*nv['mean']:+.1f}% "
              f"[{100*nv['lo']:+.1f}, {100*nv['hi']:+.1f}]")
        print(f"  Rényi efficiency (a=2.5)  : {a['renyi_efficiency']:.4f}")
        cov = payload["vocab_audit"][enc]["coverage"]
        print(f"  單字覆蓋不對稱            : 繁體對應字缺漏 "
              f"{cov['pct_trad_counterpart_missing']:.0f}% vs 簡體 "
              f"{cov['pct_simp_counterpart_missing']:.0f}%")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--ranks", default="ranks", type=Path)
    ap.add_argument("--out", default=Path("data/study.json"), type=Path)
    args = ap.parse_args()
    payload = run(args.ranks, args.out)
    summarise(payload)
    print(f"\nwrote {args.out} ({args.out.stat().st_size/1024:.0f} KB)")
